# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.16.0"
fastlane_require "yaml"
default_platform :ios

CONF = YAML.load_file('../deploy/youridfa/ios/conf.yml')

platform :ios do
  before_all do
    ENV["SLACK_URL"] = CONF["slack"]["webhookurl"]
    ENV['CRASHLYTICS_API_TOKEN'] = CONF["fabric"]["api_token"]
    ENV['CRASHLYTICS_BUILD_SECRET'] = CONF["fabric"]["build_secret"]
  end

  desc "empty"
  lane :empty do
    puts "empty"
  end

  desc "Bootstrap"
  lane :bootstrap do
    cocoapods
    sh "git submodule update --init --recursive"
    fetch_certificates
  end

  desc "Fetchs certificates and provisioning profiles"
  lane :fetch_certificates do
    match(app_identifier: "com.naoto.yamaguchi.YourIDFA.debug", type: "development", readonly: true)
    match(app_identifier: "com.naoto.yamaguchi.YourIDFA.adhoc", type: "adhoc", readonly: true)
    match(app_identifier: "com.naoto.yamaguchi.YourIDFA", type: "appstore", readonly: true)
  end

  desc "if not exists certificates and provisioning profiles, fastlane create them."
  lane :init_certificates do
    match(app_identifier: "com.naoto.yamaguchi.YourIDFA.debug", type: "development")
    match(app_identifier: "com.naoto.yamaguchi.YourIDFA.adhoc", type: "adhoc")
    match(app_identifier: "com.naoto.yamaguchi.YourIDFA", type: "appstore")
  end

  desc "Force update certificates and provisioning profiles"
  lane :force_certificates do
    match(app_identifier: "com.naoto.yamaguchi.YourIDFA.debug", type: "development", readonly: false, force: true)
    match(app_identifier: "com.naoto.yamaguchi.YourIDFA.adhoc", type: "adhoc", readonly: false, force: true)
    match(app_identifier: "com.naoto.yamaguchi.YourIDFA", type: "appstore", readonly: false, force: true)
  end

  desc "Debug build"
  lane :debug_build do
    create_temporary_keychain
    match(app_identifier: "com.naoto.yamaguchi.YourIDFA.debug", type: "development", readonly: true)
    gym(configuration: "Debug")
  end

  desc "Adhoc build"
  lane :adhoc_build do
    create_temporary_keychain
    match(app_identifier: "com.naoto.yamaguchi.YourIDFA.adhoc", type: "adhoc", readonly: true)
    gym(configuration: "Adhoc")
  end

  desc "Release build"
  lane :release_build do
    match(app_identifier: "com.naoto.yamaguchi.YourIDFA", type: "appstore", readonly: true)
    gym(configuration: "Release")
  end

  desc "Deploy Metadata"
  lane :deploy_metadata do
    deliver(metadata_only: true)
  end

  desc "Runs all the tests"
  lane :test do
    # TODO: create test scheme and run test
    # scan
  end

  desc "Submit to Fabric."
  lane :fabric do
    cocoapods
    adhoc_build
    crashlytics(
      crashlytics_path: "./Pods/Crashlytics/iOS/Crashlytics.framework",
      api_token: ENV['CRASHLYTICS_API_TOKEN'],
      build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
      ipa_path: "./build/YourIDFA(B).ipa",
      notifications: true,
      notes: "Publish Adhoc ipa.",
      groups: ["tester-1-1"]
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "YourIDFA") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    cocoapods
    release_build
    deliver(force: true) # or appstore
  end

  desc "Create temp keychain"
  private_lane :create_temporary_keychain do
    if is_ci?
      create_keychain(
        name: ENV["MATCH_KEYCHAIN_NAME"],
        password: ENV["MATCH_KEYCHAIN_PASSWORD"],
        timeout: 1800
      )
    end
  end

  after_all do |lane|
    if is_ci?
      slack(
        message: "Successfully fastlane actions :tada: "
      )
    end
  end

  error do |lane, exception|
    if is_ci?
      slack(
        message: exception.message,
        success: false
      )
    end
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
