# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.16.0"

default_platform :ios

platform :ios do
  before_all do
    # TODO: setting slack
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    cocoapods
  end

  desc "Bootstrap"
  lane :bootstrap do
    sh "git submodule update --init --recursive"
    certs
  end

  desc "Fetchs certificates and provisioning profiles"
  desc "if not existing cer and provisioning, fastlane create them"
  lane :certs do
    match(app_identifier: "com.naoto.yamaguchi.YourIDFA.debug", type: "development")
    match(app_identifier: "com.naoto.yamaguchi.YourIDFA", type: "appstore")
  end

  desc "Debug build"
  lane :debug_build do
    match(app_identifier: "com.naoto.yamaguchi.YourIDFA.debug", type: "development", readonly: true)
    gym(configuration: "Debug")
  end

  desc "Adhoc build"
  lane :adhoc_build do
    # TODO: setting adhoc build.
  end

  desc "Release build"
  lane :release_build do
    match(app_identifier: "com.naoto.yamaguchi.YourIDFA", type: "appstore")
    gym(configuration: "Release")
  end

  desc "Deploy Metadata"
  lane :deploy_metadata do
    deliver(metadata_only: true)
  end

  desc "Runs all the tests"
  lane :test do
    # TODO: create test scheme and run test
    # scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "YourIDFA") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    release_build
    deliver(force: true) # or appstore
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # TODO: post slack
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # TODO: post slack
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
